services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nextbuy
      POSTGRES_PASSWORD: nextbuy30@#
      POSTGRES_DB: nextbuy_ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
